package com.example.composetutorial

import androidx.activity.enableEdgeToEdge
import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.tooling.preview.Preview
import com.example.composetutorial.ui.theme.ComposeTutorialTheme
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.draw.clip
import androidx.compose.ui.unit.dp
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.width
import androidx.compose.material3.Surface
import androidx.compose.foundation.border
import androidx.compose.material3.MaterialTheme
import android.content.res.Configuration
import android.net.Uri
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.clickable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.animation.animateColorAsState
import androidx.compose.animation.animateContentSize
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.text.input.TextFieldLineLimits
import androidx.compose.foundation.text.input.rememberTextFieldState
import androidx.compose.material3.Button
import androidx.compose.material3.OutlinedTextField
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.livedata.observeAsState
import androidx.compose.ui.Alignment
import androidx.compose.ui.platform.LocalContext
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.navigation.NavController
import androidx.room.Entity
import androidx.room.PrimaryKey
import coil.compose.AsyncImage
import com.example.composetutorial.viewmodel.MessageViewModel
import java.io.File


// Message screen
@Composable
fun ScreenA(navController: NavController){

    val context = LocalContext.current

    var imageUri by remember { mutableStateOf<Uri?>(null) }



    LaunchedEffect(Unit) {
        val file = File(context.filesDir, "profile_picture.jpg")
        if (file.exists()) {
            imageUri = Uri.fromFile(file)
        }
    }

    val viewModel: MessageViewModel = viewModel()
    val messages by viewModel.messages.observeAsState((emptyList()))
    // code to get username from DB generated by ChatGPT 5 model
    val usernameFromDb by viewModel.username.observeAsState("")

    val textState = rememberTextFieldState()


    Column(
        modifier = Modifier.fillMaxSize(),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        Button(onClick = {
            navController.navigate("screen_B"){popUpTo("screen_B")
            {inclusive = true}
            }
        }) {
            Text("Go to Home Screen")
        }
        Row {
            OutlinedTextField(
                state = textState,
                lineLimits = TextFieldLineLimits.SingleLine,
                placeholder = {Text("Send a Message")}
            )
            Button(onClick = {
                val newMessage = Message(0,usernameFromDb, textState.text.toString())
                viewModel.addMessage(newMessage)
            }) {
                Text("Send Message")
            }
        }
        ComposeTutorialTheme {
            Surface(modifier = Modifier.fillMaxSize()) {
                Column {
                    Conversation(messages, imageUri)
                }
            }
        }


    }

}

    @Entity
    data class User(
        @PrimaryKey(autoGenerate = true)
        var id: Int = 0,
        var userName: String
    )

    @Entity
    data class Message(
        @PrimaryKey(autoGenerate = true)
        var id: Int = 0,
        var author: String,
        var body: String
    )


    @Composable
// MessageCard class from the tutorial https://developer.android.com/develop/ui/compose/tutorial
    fun MessageCard(msg: Message, uri: Uri?) {
        Row(modifier = Modifier.padding(all = 8.dp)) {
            if (uri != null){
                AsyncImage(
                    model = uri,
                    contentDescription = "profile pic",
                    modifier = Modifier
                        .size(40.dp)
                        .clip(CircleShape)
                        .border(1.5.dp, MaterialTheme.colorScheme.primary, CircleShape)
                )
            }else {
                Image(
                    painter = painterResource(R.drawable.head),
                    contentDescription = "profile pic",
                    modifier = Modifier
                        .size(40.dp)
                        .clip(CircleShape)
                        .border(1.5.dp, MaterialTheme.colorScheme.primary, CircleShape)
                )
            }
            Spacer(modifier = Modifier.width(6.dp))

            // expandable logic from the tutorial
            var isExpanded by remember { mutableStateOf(false) }

            val surfaceColor by animateColorAsState(
                if (isExpanded) MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.surface,
            )

            Column(modifier = Modifier.clickable { isExpanded = !isExpanded }) {
                Text(
                    text = msg.author,
                    color = MaterialTheme.colorScheme.secondary,
                    style = MaterialTheme.typography.titleSmall
                )

                Spacer(modifier = Modifier.height(4.dp))

                Surface(
                    shape = MaterialTheme.shapes.medium,
                    shadowElevation = 2.dp,
                    color = surfaceColor,
                    modifier = Modifier
                        .animateContentSize()
                        .padding(1.dp)

                ) {
                    Text(
                        text = msg.body,
                        modifier = Modifier.padding(all = 4.dp),
                        // If the message is expanded, we display all its content
                        // otherwise we only display the first line
                        maxLines = if (isExpanded) Int.MAX_VALUE else 2,
                        style = MaterialTheme.typography.bodyMedium
                    )
                }
            }
        }
    }

@Composable
fun Conversation(messages: List<Message>, uri: Uri?) {
    LazyColumn {
        items(messages) { message ->
            MessageCard(message, uri)
        }
    }
}




